---
#####################
# Install Python
#####################

- hosts: all
  gather_facts: false # As Python is not yet installed, we cannot gather host facts

  tasks:
    - name: Update distros
      raw: "apt-get update -y"
      become: true
      retries: 10
      delay: 20

    - name: Install Python
      raw: "apt-get -y -q install python"
      become: true
      retries: 10
      delay: 20
      # If you run this playbook immediately after Terraform, ssh may not be ready to respond yet

#######################
# Setup K8s components
#######################

- hosts: controller
  roles:
    - common
    - etcd

## Are we testing things and immediately forgetting that we commented them out?
## I think so... stop doing that....
## TODO: SET MARKER: {{ TEMP_CHANGE }}
#     - controller
#
# - hosts: worker
#   roles:
#     - common
#     - worker
