---
#######################################
# Destroy Nginx service
#######################################

# Expects kubectl being configured on the local machine
# using kubectl.yml playbook

- hosts: localhost
  connection: local

  tasks:

  - name: Destroy NGINX deployment
    command: "kubectl delete deplyoment --all"
    register: result
  - set_fact:
      deployment_status: "{{ result.stdout }}"

  - debug: msg="Deployment Status {{ deployment_status }}"

  - name: Destroy NGINX service
    command: "kubectl delete service nginx"
    register: result
  - set_fact:
      service_status: "{{ result.stdout }}"

  - debug: msg="Service Status {{ service_status }}"
