---
#######################################
# Deploy and expose Nginx service
#######################################

# Expects kubectl being configured on the local machine
# using kubectl.yml playbook

- hosts: localhost
  connection: local

  tasks:

  - name: Launching an NGINX pod
    command: "kubectl create deployment nginx --image=nginx --generator=deployment-basic/v1beta1"

  - name: Scaling NGINX to 3 pods
    command: "kubectl scale deployment nginx --replicas 3"

  - name: Expose NGINX
    command: "kubectl expose deployment nginx --port=80 --type=LoadBalancer"

  - name: Get exposed port
    command: "kubectl get service nginx --output=jsonpath='{range .spec.ports[0]}{.nodePort}'"
    register: result
  - set_fact:
      node_port: "{{ result.stdout }}"

  - debug: msg="Exposed port {{ node_port }}"
